name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.8'

    - name: Change to project directory
      run: cd visits_farmer

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Executable with PyInstaller
      run: |
        pyinstaller --onefile --noconsole streamlit_interface.py

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: WindowsExecutable
        path: dist/streamlit_interface.exe
